name: Build Kickstart ISO

on:
  push:
  workflow_dispatch:
  
jobs:

  build-job:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install mkisofs
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get -y install mkisofs

    - name: Check out the repo
      uses: actions/checkout@v3
    
    - name: Make ISO
      run: mkisofs -V "OEMDRV" -o kickstarter-${{ github.run_id }}.iso ./ks

    - name: Upload ISO image
      uses: actions/upload-artifact@v3
      with:
        name: kickstarter-${{ github.run_id }}.iso
        path: kickstarter-${{ github.run_id }}.iso
        retention-days: 2
